micronaut:
  application:
    name: mongodbdemo
mongodb.uri:  mongodb://user:password@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/test
netty:
  default:
    allocator:
      max-order: 3
db:
  name: 'test'
  collection: 'fruit'